### ISSUE TITLE
missing dependecies

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-pg-parser-python#14]
We need to have dependencies in at least one of `requirements.txt` or `setup.cfg`, else when installing this package as a dependency of another, the local dependecies in the conda file are not installed.

for `setup.cfg` for example:
```
install_requires =
  requests
  numpy
```

@claxn can you add this?

**Comment by claxn** [comment]
I agree, thanks for noting this. I have added them to the `setup.cfg` file.
