### ISSUE TITLE
How to traverse the reduce process?

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-python#15]
I am having some issues understanding how to implement the reduce process with its callback function in python, I'll be glad if you can help me!

I am able to traverse a simple process graph using the node.descendants() function.
However, I can't figure out how to deal with the reduce process and get the callback function information.
For example, with the example file openeo-pg-parser-python/tests/process_graphs/evi.json:
- The descendants of node evi is mintime
- I can get some info using node.edges, but I don't know how to use the returned ids to traverse the sub-process graph of reduce

**Comment by lforesta** [comment]
This is an excerpt from our bindings on how we go through the graph and get information about each node and its parent if needed.

@claxn maybe there are better ways with the new version?

```
from openeo_pg_parser_python.translate import translate_process_graph

def traverse_graph():
    """
    This method translates an OpenEO process graph into a list of nodes and a graph.

    """

    graph = translate_process_graph("tests/process_graphs/evi.json").sort(by='dependency')

    for cur_node in graph.nodes:
        # Check if this node contains a callback
        reducer_name = None
        reducer_dimension = None
        node_dependencies = None

        # Convert OpenEO process to eoDataReaders syntax
        # Check if this node comes from a reduce node
        for node_edge in cur_node.edges:
            # Pass dimension parameter to children of callback
            if node_edge.node_ids[0] == cur_node.id and node_edge.name == 'callback':
                parent_node_graph = graph[node_edge.node_ids[1]].content
                if 'dimension' in parent_node_graph['arguments'].keys():
                    reducer_dimension = parent_node_graph['arguments']['dimension']
                    reducer_name = cur_node.content['process_id']

        # Get node dependencies
        if not node_dependencies and cur_node.dependencies:
            node_dependencies = []
            for dependency_node in cur_node.dependencies.nodes:
                if 'callback' not in dependency_node.id:
                    node_dependencies.append(dependency_node.id)
        
        print(cur_node.name, cur_node.id)
        print(cur_node.content)
        print("reducer (name, dimensions):", reducer_name, reducer_dimension)
        print("deps:", node_dependencies)
        print('\n')
```

**Comment by claxn** [comment]
@clausmichele : I have pushed an updated version of the parser to the branch `tow_v1.0`.  Most changes were concerning a proper implementation of 'from_parameter' backtracing and a few minor changes on the user-friendliness. A first basic translation example can be found in the [README](https://github.com/Open-EO/openeo-pg-parser-python/blob/master/README.md) file. Please let me know if this does not suite your needs, then I will try to integrate your suggested improvements. @lforesta will add more examples today or tomorrow, so that other users get a better overview what you can do with the parser. Thank you!
