### ISSUE TITLE
parser fails to sort the graph

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-python#17]
I was trying to parse and sort the following process graph, but it seems to fail. I am using the latest version from the tow_v1.0 branch.
Process graph:
```
{
  "process_graph": {
    "1": {
      "process_id": "filter_temporal",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "extent": [
          "2017-04-01T00:00:00Z",
          "2017-05-01T23:59:59Z"
        ]
      }
    },
    "2": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "reducer": {
          "process_graph": {
            "1": {
              "process_id": "mean",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          },
          "parameters": [
            {
              "name": "data",
              "description": "",
              "schema": {}
            }
          ]
        },
        "dimension": "t"
      }
    },
    "3": {
      "process_id": "rename_labels",
      "arguments": {
        "data": {
          "from_node": "2"
        },
        "dimension": "bands",
        "target": [
          "G"
        ]
      }
    },
    "4": {
      "process_id": "merge_cubes",
      "arguments": {
        "cube1": {
          "from_node": "renamelabels1"
        },
        "cube2": {
          "from_node": "3"
        }
      }
    },
    "5": {
      "process_id": "filter_temporal",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "extent": [
          "2017-05-01T00:00:00Z",
          "2017-06-01T23:59:59Z"
        ]
      }
    },
    "6": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "5"
        },
        "reducer": {
          "process_graph": {
            "1": {
              "process_id": "mean",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          },
          "parameters": [
            {
              "name": "data",
              "description": "",
              "schema": {}
            }
          ]
        },
        "dimension": "t"
      }
    },
    "7": {
      "process_id": "rename_labels",
      "arguments": {
        "data": {
          "from_node": "6"
        },
        "dimension": "bands",
        "target": [
          "B"
        ]
      }
    },
    "8": {
      "process_id": "merge_cubes",
      "arguments": {
        "cube1": {
          "from_node": "4"
        },
        "cube2": {
          "from_node": "7"
        }
      }
    },
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "bands": [
          "B4"
        ],
        "id": "COPERNICUS/S2",
        "spatial_extent": {
          "west": 11.04177474975586,
          "south": 46.03653930484754,
          "east": 11.206226348876955,
          "north": 46.12417679163178
        },
        "temporal_extent": [
          "2017-03-01",
          "2017-06-01"
        ]
      }
    },
    "apply1": {
      "process_id": "apply",
      "arguments": {
        "data": {
          "from_node": "8"
        },
        "process": {
          "process_graph": {
            "linearscalerange1": {
              "process_id": "linear_scale_range",
              "arguments": {
                "inputMax": 2500,
                "inputMin": 0,
                "outputMax": 255,
                "outputMin": 0,
                "x": {
                  "from_parameter": "x"
                }
              },
              "result": true
            }
          },
          "parameters": [
            {
              "name": "x",
              "description": "",
              "schema": {}
            }
          ]
        }
      }
    },
    "saveresult1": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "apply1"
        },
        "format": "PNG",
        "options": {
          "red": "R",
          "green": "G",
          "blue": "B"
        }
      },
      "result": true
    },
    "filtertemporal1": {
      "process_id": "filter_temporal",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "extent": [
          "2017-03-01",
          "2017-04-01"
        ]
      }
    },
    "reducedimension1": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "filtertemporal1"
        },
        "dimension": "t",
        "reducer": {
          "process_graph": {
            "mean1": {
              "process_id": "mean",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          },
          "parameters": [
            {
              "name": "data",
              "description": "",
              "schema": {}
            }
          ]
        }
      }
    },
    "renamelabels1": {
      "process_id": "rename_labels",
      "arguments": {
        "data": {
          "from_node": "reducedimension1"
        },
        "dimension": "bands",
        "target": [
          "R"
        ]
      }
    }
  }
}
```

</details>
<details><summary>sorted process graph</summary>

Node ID: 3_3 
Node Name: 3 
{'arguments': {'data': {'from_node': '2_1'},
               'dimension': 'bands',
               'target': ['G']},
 'process_id': 'rename_labels'}

Node ID: 4_4 
Node Name: 4 
{'arguments': {'cube1': {'from_node': 'renamelabels1_17'},
               'cube2': {'from_node': '3_3'}},
 'process_id': 'merge_cubes'}

Node ID: 6_6 
Node Name: 6 
{'arguments': {'data': {'from_node': '5_5'},
               'dimension': 't',
               'reducer': {'from_node': '1_7'}},
 'process_id': 'reduce_dimension'}

Node ID: 7_8 
Node Name: 7 
{'arguments': {'data': {'from_node': '6_6'},
               'dimension': 'bands',
               'target': ['B']},
 'process_id': 'rename_labels'}

Node ID: 8_9 
Node Name: 8 
{'arguments': {'cube1': {'from_node': '4_4'}, 'cube2': {'from_node': '7_8'}},
 'process_id': 'merge_cubes'}

Node ID: linearscalerange1_12 
Node Name: linearscalerange1 
{'arguments': {'inputMax': 2500,
               'inputMin': 0,
               'outputMax': 255,
               'outputMin': 0,
               'x': {'from_node': '8_9'}},
 'process_id': 'linear_scale_range',
 'result': True}

Node ID: loadcollection1_10 
Node Name: loadcollection1 
{'arguments': {'bands': ['B4'],
               'id': 'COPERNICUS/S2',
               'spatial_extent': {'east': 11.206226348876955,
                                  'north': 46.12417679163178,
                                  'south': 46.03653930484754,
                                  'west': 11.04177474975586},
               'temporal_extent': ['2017-03-01', '2017-06-01']},
 'process_id': 'load_collection'}

Node ID: 5_5 
Node Name: 5 
{'arguments': {'data': {'from_node': 'loadcollection1_10'},
               'extent': ['2017-05-01T00:00:00Z', '2017-06-01T23:59:59Z']},
 'process_id': 'filter_temporal'}

Node ID: 1_7 
Node Name: 1 
{'arguments': {'data': {'from_node': '5_5'}},
 'process_id': 'mean',
 'result': True}

Node ID: apply1_11 
Node Name: apply1 
{'arguments': {'data': {'from_node': '8_9'},
               'process': {'from_node': 'linearscalerange1_12'}},
 'process_id': 'apply'}

Node ID: saveresult1_13 
Node Name: saveresult1 
{'arguments': {'data': {'from_node': 'apply1_11'},
               'format': 'PNG',
               'options': {'blue': 'B', 'green': 'G', 'red': 'R'}},
 'process_id': 'save_result',
 'result': True}

Node ID: filtertemporal1_14 
Node Name: filtertemporal1 
{'arguments': {'data': {'from_node': 'loadcollection1_10'},
               'extent': ['2017-03-01', '2017-04-01']},
 'process_id': 'filter_temporal'}

Node ID: mean1_16 
Node Name: mean1 
{'arguments': {'data': {'from_node': 'filtertemporal1_14'}},
 'process_id': 'mean',
 'result': True}

Node ID: reducedimension1_15 
Node Name: reducedimension1 
{'arguments': {'data': {'from_node': 'filtertemporal1_14'},
               'dimension': 't',
               'reducer': {'from_node': 'mean1_16'}},
 'process_id': 'reduce_dimension'}

Node ID: renamelabels1_17 
Node Name: renamelabels1 
{'arguments': {'data': {'from_node': 'reducedimension1_15'},
               'dimension': 'bands',
               'target': ['R']},
 'process_id': 'rename_labels'}

Node ID: 1_0 
Node Name: 1 
{'arguments': {'data': {'from_node': 'loadcollection1_10'},
               'extent': ['2017-04-01T00:00:00Z', '2017-05-01T23:59:59Z']},
 'process_id': 'filter_temporal'}

Node ID: 1_2 
Node Name: 1 
{'arguments': {'data': {'from_node': '1_0'}},
 'process_id': 'mean',
 'result': True}

Node ID: 2_1 
Node Name: 2 
{'arguments': {'data': {'from_node': '1_0'},
               'dimension': 't',
               'reducer': {'from_node': '1_2'}},
 'process_id': 'reduce_dimension'}
</details>

**Comment by claxn** [comment]
Thanks for reporting this - there was bug in the graph sorting, please try again!

**Comment by clausmichele** [comment]
now it seems to sort it correctly thanks.
