### ISSUE TITLE
properties for load_collection

### ISSUE THREAD

**Issue by kempenep** [Open-EO/openeo-pg-parser-python#20]
When I try to filter on properties (e..g., cloud_cover) in the load_collection process_graph, I get an exception (translate.py line 299 in adjust_from_parameters):
`ValueError: 'from_parameter' reference name 'value'can't be found or is not defined`

I tried the example with cloud_cover  from [load_collectioni](https://processes.openeo.org/#load_collection):

```
{
  "loadco1": {
    "process_id": "load_collection",
    "arguments": {
      "id": "Sentinel-2",
      "spatial_extent": {
        "west": 16.1,
        "east": 16.6,
        "north": 48.6,
        "south": 47.2
      },
      "temporal_extent": [
        "2018-01-01",
        "2019-01-01"
      ],
      "properties": {
        "eo:cloud_cover": {
          "process_graph": {
            "cc": {
              "process_id": "between",
              "arguments": {
                "x": {
                  "from_parameter": "value"
                },
                "min": 0,
                "max": 50
              },
              "result": true
            }
          }
        },
        "platform": {
          "process_graph": {
            "pf": {
              "process_id": "eq",
              "arguments": {
                "x": {
                  "from_parameter": "value"
                },
                "y": "Sentinel-2B",
                "case_sensitive": false
              },
              "result": true
            }
          }
        }
      }
    },
    "result": true
  }
}
```

**Comment by claxn** [comment]
@kempenep I dont find any `value` defined in here? You need to add a `"parameters"` entry or call `translate_process_graph(..., parameters={'value': "test"})`. Or is there something missing from the parser side @m-mohr ?

**Comment by m-mohr** [comment]
`value` is passed to the process graph from the load_collection process, see the definition of the `properties` parameter here: https://processes.openeo.org/#load_collection

**Comment by m-mohr** [comment]
Although the parameters are defined differently in load_collections and I'm trying to figure out why I did it differently there. Hmmm....

**Comment by m-mohr** [comment]
I'm working on improving the situation. 
- Try to improve how the docgen shows it:
  ![image](https://user-images.githubusercontent.com/8262166/85539498-30a6e080-b616-11ea-927f-3f07deb78ad4.png)
- Add metadata-filter subtype to properties parameter so that parsers (and clients) can better detect it

**Comment by claxn** [comment]
I had to restructure quite some parts of the code to align to this, but now it should be more flexible, also to other such processes in the future. When I now parse your process graph and print it, I get:
```
Node ID: loadco1_0 
Node Name: loadco1 
{'arguments': {'id': 'Sentinel-2',
               'properties': {'eo:cloud_cover': {'from_node': 'cc_1'},
                              'platform': {'from_node': 'pf_2'}},
               'spatial_extent': {'east': 16.6,
                                  'north': 48.6,
                                  'south': 47.2,
                                  'west': 16.1},
               'temporal_extent': ['2018-01-01', '2019-01-01']},
 'process_id': 'load_collection',
 'result': True}

Node ID: cc_1 
Node Name: cc 
{'arguments': {'max': 50, 'min': 0, 'x': {'from_node': 'loadco1_0'}},
 'process_id': 'between',
 'result': True}

Node ID: pf_2 
Node Name: pf 
{'arguments': {'case_sensitive': False,
               'x': {'from_node': 'loadco1_0'},
               'y': 'Sentinel-2B'},
 'process_id': 'eq',
 'result': True}
```
I hope this is the expected result.

**Comment by m-mohr** [comment]
Are sub process graphs always part of this output? They should be on the same level as e.g. the sub graphs in apply...

**Comment by claxn** [comment]
Only if you print the whole graph `print(process_graph)`. Internally there are two levels/depths: 0 with `loadco1_0` and 1 with `cc_1` and `pf_2`. This becomes more obvious when you plot the result:
![image](https://user-images.githubusercontent.com/15573047/85980433-acbc7200-b9e2-11ea-8170-15dfd8398c87.png)

**Comment by kempenep** [comment]
When calling the sort() function on the graph with properties, I get the error:

`graph.py:489: RuntimeWarning: graph contains a cycle, partial result is returned at /project/vendor/source/igraph/src/structural_properties.c:3448 node_order = ig.topological_sorting()`

**Comment by claxn** [comment]
@kempenep : Thanks for spotting this. I resolved it by removing the cycle, which occurs in `load_collection` being the first node in the process graph. I hope this setup works for now.

**Comment by kempenep** [comment]
All seem to work well for me now.
