### ISSUE TITLE
usage of is_reducer: isn't always a reduce_dimension process a reducer?

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-python#33]
I was wondering if it is possible to have a _reduce_dimension_ process which is not a reducer.
Otherwise, if _reduce_dimension_ is always a reducer, the is_reducer variable is not needed right?

**Comment by claxn** [comment]
`reduce_dimension` is always a reducer. The `is_reducer` should make it easier for a user to decide if the process he/she is working with is a reduce process. There are other reduce processes like `reduce_dimension_binary` and a reducer could have theoretically any name.
