### ISSUE TITLE
Process definitions outdated

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-pg-parser-python#34]
The process definitions are very much outdated, some are even not compliant with 1.0.0 (e.g. arccos as it contains a process_graph in examples). This should be updated or ideally allow the user to configure a released version of openeo-processes to work against.

Why do we need the process definitions in the pg parser in the first place? it should be agnostic of the version of the processes...

**Comment by danielFlemstrom** [comment]
I have created a git-patch that removes the examples (containing the process graph that caused the problems to us). The processes may still have to be updated, but it is a step forward. I could not create a pull request so i attach it here and hope for the best.
[remove-examples.patch.zip](https://github.com/Open-EO/openeo-pg-parser-python/files/8139008/remove-examples.patch.zip)

**Comment by m-mohr** [comment]
I think we should actually remove them: #35
