### ISSUE TITLE
Unclear error when JSON file not found

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-pg-parser-python#6]
Currently, when the input JSON file (or related python dict) is not found, the following error is returned:
`UnboundLocalError: local variable 'pg_dict' referenced before assignment`

This is not clear and very unfriendly to debug, add check if input file exists or if input dict is not empty.

**Comment by claxn** [comment]
Please grant me developer rights so that I can create a new branch and participate, thanks.

**Comment by claxn** [comment]
Sry, it worked now, there was something wrong with the user settings. Coming back to the issue:
The code at the beginning of `translate_graph `does not check the input arguments correctly (it worked in the original version). I fixed it and will open a PR.
