### ISSUE TITLE
use deepcopy on input pg as dict

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-pg-parser-python#9]
Assuming `process_graph_json` is of type dict, the following returns an error:

```
graph1 = translate_graph(process_graph_json)
graph2 = translate_graph(process_graph_json)
```

because `translate_graph` ìnternally modifies `process_graph_json`

Can be solved by using `copy.deepcopy()` when reading the file/dict initially

**Comment by claxn** [comment]
@lforesta: The bug was fixed some time ago, please reopen the issue if it occurs again.
